sudo: required

services:
  - docker

language: java
jdk:
  - openjdk8

after_script:
  - docker-compose build
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mixomat/cvmaker-api:latest
