sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

after_script:
  - docker-compose build

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

