app:
  build: .
  environment:
    - SPRING_DATA_MONGODB_HOST=mongo
  ports:
    - "8080:8080"
  links:
    - mongo
  volumes_from:
    - data
mongo:
  image: mongo:3.2
  expose:
    - "27017"
  ports:
    - "27017:27017"
  volumes_from:
    - data
data:
  image: busybox
  command: /bin/true
  volumes:
    - "/Users/marc/projects/docker/data/mongo:/data"
